### ISSUE TITLE
app.html doesn't work, how to add attrubute to html tag?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/starter#12]
When I add app.html in root with:

```
<!DOCTYPE html>
<html {{ lang="ru" }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}
  </body>
</html>
```

It doesn't add that attribute to html tag. How to add attrubute to html tag?

**Comment by Atinux** [comment]
Actually the `app.html` is in the `0.10` release (not available yet).

But you can use [head elements](https://nuxtjs.org/api/configuration-head/#the-head-property) already in your `nuxt.config.js`:
```js
module.exports = {
  head: {
    htmlAttrs: {
      lang: 'ru'
    }
  }
}
```

**Comment by kodekrendel** [comment]
@Atinux that's great! But here's another issue. Can I add `<html itemscope>`? If I add `itemscope: ''` then I got `<html itemscope="">`

**Comment by kodekrendel** [comment]
If I use `itemscope: undefined` then nothing shows at all. I think it's a bug @Atinux because here https://github.com/declandewet/vue-meta#recognized-metainfo-properties

there's an example:

```
{
  metaInfo: {
    htmlAttrs: {
      foo: 'bar',
      amp: undefined
    }
  }
}
```

```
<html foo="bar" amp></title>
```

**Comment by Atinux** [comment]
@kodekrendel This is an issue related to [vue-meta](https://github.com/declandewet/vue-meta), can you create an issue there please?

**Comment by kodekrendel** [comment]
@Atinux done https://github.com/declandewet/vue-meta/issues/68
