### ISSUE TITLE
Cannot start on CodeSandbox

### ISSUE THREAD

**Issue by Tahul** [nuxt/starter#142]
I've encountered 2 issues while trying to start the CodeSandbox template (that is accessible here [Get Started](https://v3.nuxtjs.org/getting-started/installation)):

- First is telemetry that gets prompted in a read-only terminal
	- https://github.com/nuxt/starter/pull/141
- Second is this error, which I've not seen before:
	- <img width="700" alt="CleanShot 2022-10-25 at 00 41 57@2x" src="https://user-images.githubusercontent.com/1385263/197643518-569977cc-3764-470a-9322-32ded35f1e3a.png">

**Comment by nobkd** [comment]
Maybe this helps: https://github.com/nuxt/content/issues/1630#issuecomment-1286651075

**Comment by danielroe** [comment]
Apologies. This has been resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) via https://github.com/nuxt/framework/pull/8299, and will be fixed in the next RC.

Also see https://github.com/nuxt/nuxt.js/issues/15246.

**Comment by danielroe** [comment]
This is now resolved in RC13.
