### ISSUE TITLE
Remove stackblitz and codesandbox branches

### ISSUE THREAD

**Issue by atinux** [nuxt/starter#15]
From checking directly, we don't need them anymore:
- CodeSandBox: https://codesandbox.io/s/github/nuxt/starter/tree/v3
- StackBlitz: https://stackblitz.com/fork/github/nuxt/starter/tree/v3

What do you think @pi0 ?

**Comment by atinux** [comment]
Is the `v3-vercel` necessary as well? or can we simply add the deploy button (both Vercel and Netlify) in the v3 readme?

https://github.com/nuxt/starter/tree/v3-vercel

**Comment by pi0** [comment]
For codesandbox, we are enabling couple of more options (https://github.com/nuxt/starter/blob/v3-codesandbox/sandbox.config.json) such as redirect loop and default view. Can we add them to codesandbox template for `nuxt` directly? (We also have a `postinstall` to avoid caching lockfile)

**Comment by atinux** [comment]
I think I am fine keeping these branches to ajust the behavior based on the platforms changes, only not listing them directly since there are made to be opened online, see #16
