### ISSUE TITLE
after starter serve, visited page out this error

### ISSUE THREAD

**Issue by chanhuiwumeng** [nuxt/starter#154]
No response returned from render handler: /__nuxt_error?url=/&statusCode=500&statusMessage=Vite+Error&message=[vite-node]+[ERR_INVALID_URL_SCHEME]+/node_modules/ufo/dist/index.mjs&stack=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+/node_modules/ufo/dist/index.mjs%3C/span%3E%3C/pre%3E&data

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt.js/issues/15362.
