### ISSUE TITLE
consider more specific `include` options for module template

### ISSUE THREAD

**Issue by danielroe** [nuxt/starter#164]
see https://github.com/nuxt/starter/pull/163 for context

**Comment by atinux** [comment]
Would it be fixed by using the 

```ts
typescript: {
  includeWorkspace: true
}
```

In the `playground/nuxt.config.ts` @danielroe ?

**Comment by danielroe** [comment]
After investigating, it *should* be fixed with https://github.com/nuxt/starter/commit/94e0f8c164930aa326f37708febdafcaaf5c8a54.
