### ISSUE TITLE
Cannot start on Codesandbox

### ISSUE THREAD

**Issue by jwhazel** [nuxt/starter#188]
I see that there was a similar issue for #142, but this seems to be a different cause.
https://codesandbox.io/s/github/nuxt/starter/tree/v3-codesandbox
Seems to die on this error: `Cannot start nuxt:  (0 , _nuxt.defineNuxtConfig) is not a function at nuxt.config.ts:4:43`

I poked around at it, but not sure what the root cause is.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/starter/commit/6c1b65222eac131b7c4b9c80814ae9236ff64dd8 - we removed the need to import defineNuxtConfig explicitly

**Comment by danielroe** [comment]
Thanks for reporting!
