### ISSUE TITLE
Better default for store integration

### ISSUE THREAD

**Issue by katerlouis** [nuxt/starter#189]
awesome @danielroe considered better store default integration 😍 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/1983382/207555808-ef89e30a-035d-4759-a87e-aab66e955097.png">

Also wondering: is templating like this on initialization supposed to replace a scaffolding solution like create-nuxt-app? I am really missing a wizard like this in the nuxt3 universe. Linting with extends, css preprocessor, git, modules, store :'(

**Comment by atinux** [comment]
Related to #134

**Comment by katerlouis** [comment]
Thanks @Atinux – I think we can close this one then.
