### ISSUE TITLE
Run Npx nuxt/nuxi init Error. can't init the nuxt3 project.

### ISSUE THREAD

**Issue by yangxu52** [nuxt/starter#199]
run "npx nuxi init -t v3 nuxt-app" or "npx nuxt init" or "npx nuxi init" failed, any file be not created. Not network issue ,I try a lots of times(using/nouse proxy, change proxy node and use anthoer network environment) 
show my commend and print
![image](https://user-images.githubusercontent.com/64672399/209493342-fc0c6304-29ba-44fa-8745-d25e74124f9a.png)
```
D:\123>npx nuxi init -t v3 nuxt-app
Nuxi 3.0.0

 ERROR  Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: getaddrinfo ENOENT raw.githubusercontent.com                              10:47:24

  at /D:/dev/node/node_cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:15133:11
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async downloadTemplate (/D:/dev/node/node_cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:15132:20)
  at async Object.invoke (/D:/dev/node/node_cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:15200:15)
  at async _main (/D:/dev/node/node_cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by mohsin** [comment]
Same. Except I got:
```
Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: write EPROTO 8601909888:error:140943E8:SSL routines:ssl3_read_bytes:reason(1000):ssl/record/rec_layer_s3.c:1556:SSL alert number 0
```

**Comment by ColinRosati** [comment]
Out of curiosity what node version are you using?

**Comment by mohsin** [comment]
So I found the issue. This has to do with nuxi using [raw.githubusercontentap.com](https://github.com/nuxt/framework/blob/2f5349503312fddd8337bfb78c9cd0b618c08c08/packages/nuxi/src/commands/init.ts#L9) as the default registry and for some reason it failed to load on my mac. I manually overwrote the `/etc/hosts` to point to githubusercontent's IP and ran the command again. It works fine now!

**Comment by danielroe** [comment]
@mohsin Would you try `npx nuxi@latest` to ensure you're using the latest version? This should have been resolved - see https://github.com/nuxt/nuxt.js/issues/15101.

**Comment by mohsin** [comment]
@danielroe Yes, it does work without the hosts entry now. Perfect!

**Comment by yangxu52** [comment]
> 出于好奇，您使用的是什么节点版本？

16.17.0

**Comment by yangxu52** [comment]
> Out of curiosity what node version are you using?

16.17.0

**Comment by coderwyd** [comment]
![图片](https://user-images.githubusercontent.com/53386850/228757787-616474d3-5820-4688-a64f-b3ef44ec24ca.png)
