### ISSUE TITLE
Update module template

### ISSUE THREAD

**Issue by atinux** [nuxt/starter#203]
https://github.com/nuxt/starter/tree/module

- [ ] Improve readme (Add description, installation, usage, module development and note for module-builder)
- [ ] Add `@nuxt/eslint-config`
- [ ] Setup a release script (release-it or changelogen)
- [ ] Add a test with `@nuxt/test-utils`

**Comment by pi0** [comment]
For the release script, we should use `changelogen --release` ([example](https://github.com/nuxt-experiments/nuxt-config-schema/blob/main/package.json#L22)). It guarantees forward compatibility with module builder integration and consistent changelogs we can render on website.

Entry `module.ts` should also be simplified a little bit using kit and remove defaults I see are often preserved in published modules.

I think would be also a good time to introduce basic prettier wyt @danielroe ?
