### ISSUE TITLE
Layer template TS Language Server

### ISSUE THREAD

**Issue by droutin** [nuxt/starter#273]
Hello,

When hovering above, for example, `defineNuxtConfig` in `nuxt.config.ts` starts loading of types. But it fails with this error message
![image](https://user-images.githubusercontent.com/17362753/221946529-911fcc50-7f60-4348-ba98-d451d1aa9999.png)
I have installed fresh layer template with command `npx nuxi init nuxt-layer-tsls --template layer`
Problem is in tsconfig.json. It wants types from .playground but, npm script `npm run dev` generates types with command `nuxi prepare` to root, not .playground.

**Comment by atinux** [comment]
Should be now fixed via https://github.com/nuxt/starter/commit/2b43522dfd72b8a6e5bbcf23257ff91368f4757c
