### ISSUE TITLE
Cannot find name 'defineNuxtConfig'.ts(2304)

### ISSUE THREAD

**Issue by wypratama** [nuxt/starter#319]
I tried to install Nuxt 3 layers inside a monorepo with turborepo. and I somehow get error with typescript where it's seems to not able to figure out nuxt types, but everything is fine inside .playground folder.

![cannot find name](https://i.stack.imgur.com/fx6kB.png)

![cannot find name](https://i.stack.imgur.com/ye7sx.png)

how can i fix this?

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by wypratama** [comment]
hi @danielroe, I managed to fix it by adding:
`
typescript: {
    includeWorkspace: true,
  },
`
to the nuxt.config.ts inside .playground. Thanks!

**Comment by avxkim** [comment]
@danielroe i think this must be documented or set by default, what do you think?

**Comment by danielroe** [comment]
I believe this is [set by default](https://github.com/nuxt/starter/blob/layer/.nuxtrc) in the layer starter, but if it isn't working we should raise a new issue (with reproduction) first - and then update.

**Comment by avxkim** [comment]
No, i'm using module starter and it's not.

**Comment by danielroe** [comment]
Oh. This issue was about the layers starter. The Nuxt module starter uses new stub mode by default. Are you using that?

**Comment by avxkim** [comment]
Guess no :) how can i use it?

**Comment by danielroe** [comment]
Check the module branch on this repo.

**Comment by avxkim** [comment]
if you mean this: https://github.com/nuxt/starter/tree/module
i've cloned this repo and it has issues without `typescript: { includeWorkspace: true, }` in nuxt.config.ts

**Comment by danielroe** [comment]
Do you have a reproduction? Feel free to create an issue to track it!

**Comment by avxkim** [comment]
@danielroe 
[test-module.zip](https://github.com/nuxt/starter/files/14626199/test-module.zip)

1. `pnpm i`
2. `pnpm dev`
3. take a look at "src/runtime/components/test.vue

<img width="569" alt="image" src="https://github.com/nuxt/starter/assets/5739191/9708d8dc-80b6-493a-bb23-8e231d1eb86f">

It doesn't have `.nuxtrc` by default (i mean module starter, but layer does)

I also created PR: https://github.com/nuxt/starter/pull/685

**Comment by danielroe** [comment]
@avxkim  that is actually correct. It is flagging up an issue you will have when you publish the module to npm, where auto imports are not supported.

**Comment by avxkim** [comment]
@danielroe but even if i use imports, like this:

`import { ref } from '#imports'` it still flags it as error. Are you sure we don't need `.nuxtrc` ?

**Comment by danielroe** [comment]
Can you provide a reproduction? 🙏
