### ISSUE TITLE
Starter warns about `@types/node` peer dependencies

### ISSUE THREAD

**Issue by pi0** [nuxt/starter#339]
Using a fresh nuxt project made with `nuxt init` and pnpm i get:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/5158436/232491393-6ab67ed2-a35a-4201-9a88-332b9cbce044.png">

We need to add `@types/node` and `typescript` to the devDependencies of all starters imo.

**Comment by danielroe** [comment]
Quite right!
