### ISSUE TITLE
@nuxt/devtools@0.6.7 invalid: "latest"

### ISSUE THREAD

**Issue by yongqi02** [nuxt/starter#414]
# Environment

- Operating System: Darwin
- Node Version: v18.16.0
- Nuxt Version:  3.6.2
- Nitro Version: 2.5.2
- Package Manager: npm@9.7.2
- Builder: nuxi@3.6.2

# Description

I use nuxt to create nuxt projects

<img width="809" alt="image" src="https://github.com/nuxt/starter/assets/129808054/22dfd8f2-0a06-4680-8618-ad7b10b5d4c9">

Then, the error that occurred when running "npm ls"

<img width="851" alt="image" src="https://github.com/nuxt/starter/assets/129808054/685bb9fb-81b2-41fb-b28a-405e1e6a896b">

But the 'yarn list' can run normally

<img width="402" alt="image" src="https://github.com/nuxt/starter/assets/129808054/d2240465-92c1-4339-b22a-323bb21cbdb6">

This error will not affect the normal operation of the project

<img width="515" alt="image" src="https://github.com/nuxt/starter/assets/129808054/5660ea9c-06be-4e2d-a906-ef4f107eee3c">

It seems that it only affects the 'npm list' instruction

<img width="854" alt="image" src="https://github.com/nuxt/starter/assets/129808054/739442bb-e00f-4cd0-9a2b-f5154a997cde">

# Solution

I think there was an error with this' @ latest '

<img width="212" alt="image" src="https://github.com/nuxt/starter/assets/129808054/f49ea36a-cd2b-4b74-b62a-bfbbe36ab704">

The npm list command will only return to normal after I specify the version

<img width="223" alt="image" src="https://github.com/nuxt/starter/assets/129808054/d00c1eaf-44b9-469e-928d-43954d4aca58">

<img width="350" alt="image" src="https://github.com/nuxt/starter/assets/129808054/0961c6c4-50a4-4461-a918-0ce98b0dcf91">

**Comment by danielroe** [comment]
`latest` is a valid tag so this seems like an npm bug.
