### ISSUE TITLE
Should .npmrc be ignored?

### ISSUE THREAD

**Issue by HotariTobu** [nuxt/starter#464]
I created a Nuxt 3 project with the starter repository (thank you😊).

After I uploaded the project on GitHub as a public repository, GitGuardian warned me not to include `.npmrc`.

Therefore, it can be better to add `.npmrc` into `.gitignore` without removing `.npmrc`.

**Comment by danielroe** [comment]
No, it should not be gitignored. It's important to be there so that your CI/CD will also shamefully-hoist dependencies.
