### ISSUE TITLE
I can't down template with command  "npx nuxi init nuxt-app"

### ISSUE THREAD

**Issue by MrChen0521** [nuxt/starter#47]
when i  run the command "npx nuxi init nuxt-app", I got this error:
Nuxt CLI v3.0.0-rc.3                                                  11:31:38

 WARN  could not fetch remote https://github.com/nuxt/starter     
 WARN  Make sure you have installed git correctly

**Comment by atinux** [comment]
You can use:
```bash
npx nuxi@latest init nuxt-app
```


Or install it globally with:

```bash
npm install -g nuxi
```
