### ISSUE TITLE
Unable to create nuxt3

### ISSUE THREAD

**Issue by jsxiaosi** [nuxt/starter#48]
when i run the command "npx nuxi init nuxt-app", I got this error:
Nuxt CLI v3.0.0-rc.3

WARN could not fetch remote https://github.com/nuxt/starter
WARN Make sure you have installed git correctly

#47 I looked up this record in the question and did the following operations according to the reply inside
```
npx nuxi@latest init nuxt-app
```
or
```
npm install -g nuxi
```

It seems that the problem cannot be solved, and the same error is reported

My node version is LST v16.15.1
My git version is 2.36.1

**Comment by luck0921** [comment]
me too 
![image](https://user-images.githubusercontent.com/64535954/173313935-381f3fc2-3c62-4cb6-a4eb-ed7ecf1ff90d.png)

**Comment by atinux** [comment]
Just tried again and works for me.

Are you behind any proxy or VPN?

**Comment by Aruelius** [comment]
try this:

`npm install -g nuxi`

then change file:

`C:\Users\{username}\AppData\Roaming\npm\node_modules\nuxi\dist\chunks\init.mjs`

change the proxy address at 9991 lines:

`this.proxy = 'http://127.0.0.1:10800';`

then use:

`nuxi init your-app-name`

**Comment by jsxiaosi** [comment]
> 刚刚再次尝试并为我工作。
> 
> 您是否支持任何代理或 VPN？

Yes, I support it, but he can work normally now

I have verified that it is the problem of proxy and VPN

The above problem occurs after I try to turn off the proxy and VPN

**Comment by dawnlion0305** [comment]
I have the problem too. I'm not behind any proxy or VPN. 

![image](https://user-images.githubusercontent.com/46887188/176487321-ab3692ac-8c8b-41e4-843a-b35e5ba2e875.png)

My node version is LST v16.15.1.
My git version is 2.37.0.

And I try this:
@Aruelius 
> try this:
> 
> `npm install -g nuxi`
> 
> then change file:
> 
> `C:\Users\{username}\AppData\Roaming\npm\node_modules\nuxi\dist\chunks\init.mjs`
> 
> change the proxy address at 9991 lines:
> 
> `this.proxy = 'http://127.0.0.1:10800';`
> 
> then use:
> 
> `nuxi init your-app-name`

But the problem happen again. 
Like this :

![捕获2](https://user-images.githubusercontent.com/46887188/176486878-10604c6d-cc62-4160-b7fc-1c2fd367574a.PNG)
 
The above problem occurs again and again.  I try as I may search any way about the problem but can't resolve like this.

**Comment by SuperCuteXiaoSi** [comment]
> 

You should open the proxy or VPN to create the project!

**Comment by jsxiaosi** [comment]
> I have the problem too. I'm not behind any proxy or VPN.
> 
> ![image](https://user-images.githubusercontent.com/46887188/176487321-ab3692ac-8c8b-41e4-843a-b35e5ba2e875.png)
> 
> My node version is LST v16.15.1. My git version is 2.37.0.
> 
> And I try this: @Aruelius
> 
> > try this:
> > `npm install -g nuxi`
> > then change file:
> > `C:\Users\{username}\AppData\Roaming\npm\node_modules\nuxi\dist\chunks\init.mjs`
> > change the proxy address at 9991 lines:
> > `this.proxy = 'http://127.0.0.1:10800';`
> > then use:
> > `nuxi init your-app-name`
> 
> But the problem happen again. Like this :
> 
> ![捕获2](https://user-images.githubusercontent.com/46887188/176486878-10604c6d-cc62-4160-b7fc-1c2fd367574a.PNG)
> 
> The above problem occurs again and again. I try as I may search any way about the problem but can't resolve like this.

You should open the proxy or VPN to create the project!

**Comment by dawnlion0305** [comment]
Thanks! That's very useful! @SuperCuteXiaoSi
