### ISSUE TITLE
Vue & Nuxt primitives are not available

### ISSUE THREAD

**Issue by sumerokr** [nuxt/starter#505]
Dear Nuxt team,

I noticed 2 issues with module starter template.

## issue 1
Nuxt throws 500 error when you try to use a `ref` in the injected plugin. I believe that worked before.
See https://stackblitz.com/edit/github-5m1frr?file=src%2Fruntime%2Fplugin.ts

## issue 2
Nuxt throws 500 error when you try to use a `useNuxtApp` in the playground/app.vue file. Explicit import helps, but I assume it should be auto-imported.
See https://stackblitz.com/edit/github-5m1frr?file=playground%2Fapp.vue

**Comment by danielroe** [comment]
These need to be imported explicitly from `#imports` within module runtime.

**Comment by sumerokr** [comment]
@danielroe thanks for the quick reply. Ok, will import them explicitly.
Just to make it clear
```
// playground/app.vue

import { useNuxtApp } from '#app'
const { $cookieConsent } = useNuxtApp()
```

```
// src/runtime/plugin.ts

import { defineNuxtPlugin } from '#app'
import { ref } from '#imports'

export default defineNuxtPlugin((nuxtApp) => {
  const something = ref('it works')
})

```
