### ISSUE TITLE
Types are lost when assigned to runtimeConfig

### ISSUE THREAD

**Issue by sumerokr** [nuxt/starter#507]
Hi,

My module has options like
```
type User = {
  name: string;
  age: number;
};

export interface ModuleOptions {
  users: User[]
}
```

I pass this information to runtime via `runtimeConfig`
```
export default defineNuxtModule<ModuleOptions>({
  meta: {
    configKey: 'myModule',
  },
  defaults: {
    users: [],
  },
  setup (options, nuxt) {
    nuxt.options.runtimeConfig.public.myModule = {
      users: options.users,
    }

    const resolver = createResolver(import.meta.url)
    addPlugin(resolver.resolve('./runtime/plugin'))
  }
})
```

While `options.users` that is being assigned to runtime config has type `(property) ModuleOptions.users: User[]`,
the `runtimeConfig.public.myModule.users` has type `(property) users: {}[]`. It also happens in other files, like in runtime/plugin.ts, for example, when you want to use `users` from the above example.

As you can see `{ name: string; age: number; }[]` become just `{}[]`. Is that expected? And if so, how can we improve/adjust these types.

reproduction link: https://stackblitz.com/edit/github-wvc2k7?file=src%2Fmodule.ts

**Comment by danielroe** [comment]
You can manually declare the types:
https://nuxt.com/docs/guide/going-further/runtime-config#manually-typing-runtime-config

**Comment by danielroe** [comment]
We can track the issue reported in https://github.com/nuxt/nuxt/issues/12400.

**Comment by sumerokr** [comment]
> You can manually declare the types:
https://nuxt.com/docs/guide/going-further/runtime-config#manually-typing-runtime-config

Will give it a try, thanks!
