### ISSUE TITLE
Feature: remote repositories

### ISSUE THREAD

**Issue by Triloworld** [nuxt/starter#509]
We try to use part of unjs engine to download remote package by this:

```js
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  extends: ["github:org-name/repo-name"]
});

```

Rollup issues, there is problem with alias for directories - this is propably connected: https://github.com/nuxt/nuxt/issues/18448

We get some point resolve by using alias config and in debug there is downloaded repo but not linked same like monorepo have.
As we found out - npm isn't init after download and node_modules isn't found.
There are issue by multiple node_modules that will show `Error 500` same as there in this topic:
https://github.com/nuxt/nuxt/issues/14928

This engine will be used in future? Nice to add in documentation and when someone search it : https://unstorage.unjs.io/drivers/github

Documentation should say that remote paths aren't available like there right now: 
https://github.com/nuxt-contrib/nuxt-extend#parent

This topic is only to have question and add information when someone search for that option

**Comment by pi0** [comment]
Hi. Feel free to open an issue in [unjs/c12](https://github.com/unjs/c12) is not working as expected when extending a remote layer ([unjs/giget](https://github.com/unjs/giget) is used behind the scenes. unjs is not used for this nor nuxt-extend which was an experiment for nuxt 2)

**Comment by Triloworld** [comment]
Big Thanks @pi0  I see that is on develop and not for production ready but in your head. Ofc i will. 
Your response help with documentation there :)
