### ISSUE TITLE
shamefully-hoist in .npmrc

### ISSUE THREAD

**Issue by Celibioux** [nuxt/starter#547]
the .npmrc still keep the shamefully-hoist= true

**Comment by angelhdzmultimedia** [comment]
I don't know if I should open a new issue, but anyways, had an issue with nuxt-quasar-ui today https://github.com/Maiquu/nuxt-quasar/issues/75

And went right here to the starter template to confirm that it doesn't come with the .npmrc file and shamefully-hoist= true anymore, as they mentioned in Nuxt Nation that is not required anymore, that just installing vue and vue-router explicitly is enough.

But I think there will still be libraries that will require it.

Now I'm wondering if I should always use it when using pnpm or not... 🤔🥴
