### ISSUE TITLE
New layer fails typecheck

### ISSUE THREAD

**Issue by marr** [nuxt/starter#554]
I created a new layer project using `npx nuxi init -t layer` and when I run `npx nuxi typecheck` on the fresh project, there is a failure. You can see the output here:

```
.playground/nuxt.config.ts:2:3 - error TS2322: Type 'string' is not assignable to type '(string | [(string | undefined)?, ({ [x: string]: any; meta?: { [x: string]: any; name?: string | undefined; } | undefined; giget?: { provider?: string | undefined; force?: boolean | undefined; ... 7 more ...; auth?: string | undefined; } | undefined; overrides?: { ...; } | undefined; } | undefined)?] | undefined)[]'.

2   extends: '..'
    ~~~~~~~

  node_modules/@nuxt/schema/dist/index.d.ts:1135:2
    1135  extends: (string|string|[string, SourceOptions?])[],
          ~~~~~~~
    The expected type comes from property 'extends' which is declared here on type 'InputConfig<NuxtConfig, ConfigLayerMeta>'


Found 1 error in .playground/nuxt.config.ts:2
```

I'm not a TypeScript expert so I'm not sure how this would be addressed. Maybe just changing to:

`extends: ['..']`

would fix

**Comment by shinGangan** [comment]
Hi @marr , is this issue already resolved?
(From the PR, it seems to have been resolved...)

I'm trying to use `nuxi init -t layer`, so if it's not resolved, I'll try to address it in advance.

**Comment by shinGangan** [comment]
@danielroe , thanks for closed this 💚
