### ISSUE TITLE
CodeSandbox via `nuxt.new` is broken

### ISSUE THREAD

**Issue by TheAlexLichter** [nuxt/starter#599]
1. Click on https://nuxt.new/c/v3
2. See "Setup failed"

Seems like old devtool dep though "latest" is selected 🤔

<img width="1713" alt="image" src="https://github.com/nuxt/starter/assets/640208/785a6f85-4e17-4a99-b2d0-bb5d45e6acc4">

**Comment by danielroe** [comment]
Shall we drop the explicit dependency?

cc: @antfu

**Comment by antfu** [comment]
That's weird that latest is not latest. Sure I think we could remove the explicit dep.

**Comment by antfu** [comment]
Should be fixed now. Thanks.
