### ISSUE TITLE
Nuxt module : IDE doesn't recognize vue functions.

### ISSUE THREAD

**Issue by guirak** [nuxt/starter#615]
Hello, 

I create a new Nuxt module : 

`npx nuxi init -t module my-module`

Next, I correct an error with package dependencies changing the vitest  version in package.json  :

` "vitest": "^1.1.0",`

I launch the command to prepare the project : 
```
npm i
npm run dev:prepare
```

I create a component in the runtime directory : runtime/components/TestComponent.vue

Inside this component, the IDE doesn't know the vuejs functions : ref, watch, ... 
`
TS2304: Cannot find name ref`

When creating the component in the playground, the function are well recognized. 

I encounter the problem in all IDE : IntelliJ, WebStorm, Visual Studio. 
When launching the playground with the "npm run dev" command, all work fine event if the IDE display this error. 

I have tried several settings in the IDE but non of them solve the problem. 

Have you any idea ?

Regards,

**Comment by TheAlexLichter** [comment]
@guirak Did you use Volar and VSCode? Did you also utilize the Takeover mode?

**Comment by guirak** [comment]
Hi Manil, 

Sorry for this late answer.

I'm mainly using intellij ultimate but to verify the problem I've also tested with Webstorm and VSCode.
I have the problem with all.

In intellij, I have configured it to use volar instead choosing automatically but this doesn't solve the problem...

**Comment by guirak** [comment]
Maybe the following issue can explain the problem :
https://github.com/nuxt/module-builder/issues/197#issue-2005824428

**Comment by danielroe** [comment]
The reason this is the case is that you should import them from `#imports`. While it might work in the playground without this, it won't work when you compile your module and distribute via `node_modules`. So this is actually a safeguard for you.

**Comment by guirak** [comment]
Thank you. It's working :)
