### ISSUE TITLE
未知的问题，没有端口，页面却诡异的显示出Nuxt 3 Vitesse What's your name? GO  [Default Layout]

### ISSUE THREAD

**Issue by abucd** [nuxt/starter#681]
我查找了一下端口3000，找不到任何进程，
我又去浏览器查看了一下本地端口3000，
页面被nuxt占领了，但是没有样式，
我又重新打开了一下浏览器，依旧如此。
我又dev了一下，还是3000端口，
我在vscode中打开了2个终端，再次dev了一下，
发现3001的本地端口没有任何问题。
我决定不使用3000端口了。

**Comment by abucd** [comment]
![image](https://github.com/nuxt/starter/assets/136567844/8eb8c3a8-8940-44f8-9708-6bc8a06b02f7)

**Comment by abucd** [comment]
![image](https://github.com/nuxt/starter/assets/136567844/646a5937-0957-4ffd-9ef2-289465d1a034)

**Comment by abucd** [comment]
我重新启动了电脑，依旧如此。

**Comment by nekorrrr** [comment]
是不是有什么服务在启动，这个库好像都是国外的人在维护，所以用中文应该不行，你最好用英文问。
另外vitesse应该是另外一个开源项目，你如果是用那个vitesse-nuxt的库的代码，那么你应该在另一个库去问。

顺便一提，我怀疑是浏览器的缓存，你刷新一下看那个网络，看看状态码旁边是不是有括号(from disk)
