### ISSUE TITLE
Add postinstall script

### ISSUE THREAD

**Issue by HugoRCD** [nuxt/starter#718]
Wouldn't it be simpler for development to add a 'postinstall' script to do the dev:prepare so that development can start immediately after the dependencies have been installed?

Like this ?
![CleanShot 2024-04-15 at 16 22 43](https://github.com/nuxt/starter/assets/71938701/82ce7455-ba3b-435d-af5a-b5694d32f4e8)

**Comment by danielroe** [comment]
This would apply to projects installing your module and would fail in that context. They should have their own `postinstall` script.

**Comment by HugoRCD** [comment]
Ah, okay, I did know that indeed, thanks!
