### ISSUE TITLE
Why are dependencies not under `devDependencies`?

### ISSUE THREAD

**Issue by meirroth** [nuxt/starter#723]
https://github.com/nuxt/starter/blob/5ee03e5726aa48e71648c6eb60055051b0dc04d3/package.json#L12-L15
I see they were moved by @danielroe here: https://github.com/nuxt/starter/commit/ae15839727b873b546ac9ef36d5bb3964bac77e0 Any idea why? 
I noticed this after `nuxi module add` based where to add dependency from this, see: https://github.com/nuxt/eslint/issues/422#issuecomment-2102614337

**Comment by atinux** [comment]
It's more a flavor about how you want to split your dependencies as in the final bundle, only the used dependencies are traced and included. So all can be in dev dependencies.

I personally (and Daniel too) use `dependencies` to have the project dependencies and use `devDependencies` for everything related to development (testing, linting, typescript, bundling)

**Comment by meirroth** [comment]
@Atinux Thank you for the explanation!

**Comment by VladislavYakonyuk** [comment]
> It's more a flavor about how you want to split your dependencies as in the final bundle, only the used dependencies are traced and included. So all can be in dev dependencies.
> 
> I personally (and Daniel too) use `dependencies` to have the project dependencies and use `devDependencies` for everything related to development (testing, linting, typescript, bundling)

Hi! I apologize, of course, for the stupid question. What is the reason for storing everything in “devDependencies”? As far as I understand, it's just a matter of taste?

**Comment by pi0** [comment]
Issue with putting build tools in `dependencies` is with deployment providers/setups that install all dependencies in project root in production (while not needed and `.output` standalone has everything), otherwise just matter of choice.
