### ISSUE TITLE
nuxt.new layers starter is completely wrong

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/starter#801]
### Environment

n/a

### Reproduction

https://nuxt.new/
https://github.com/nuxt/starter/tree/layer

### Describe the bug

The https://nuxt.new/ layers starter template is completely wrong. It doesn't even use Nuxt layers or the `extends` config feature (or the new `layers/` directory that was recently introduced). Perhaps this starter is outdated? My suggestion is to update it to actually showcase using layers, especially now that we have `layers` directory that auto-registers the layers.

It would be nice to also have a more complete solution where it showcases how to use server routes within layers, components, composables, config etc. The current starter seems very... lacking.

I would be willing to contribute. Should I send in a PR?

What do you think?

**Comment by danielroe** [comment]
I think it's meant to be a starter for creating a layer to be published to npm. But PRs would be very welcome 🙏

**Comment by martinszeltins** [comment]
> I think it's meant to be a starter for creating a layer to be published to npm. But PRs would be very welcome 🙏

Oh that makes sense then. At first glace it seemed like it was for initing a new Nuxt project but with layers.
