### ISSUE TITLE
Release check failed

### ISSUE THREAD

**Issue by Ena-Heleneto** [nuxt/starter#850]
When I cloned a new project to my local environment and then executed the release script, it didn't pass. The error is as follows.

![image](https://github.com/user-attachments/assets/76f640fb-813a-486e-bcb1-c7647b6b4859)

I need some help,thanks

**Comment by danielroe** [comment]
you need to run the `dev:prepare` step first.

**Comment by Ena-Heleneto** [comment]
ok，thank you
