### ISSUE TITLE
How to reference data injected through dependency injection.

### ISSUE THREAD

**Issue by Ena-Heleneto** [nuxt/starter#865]
I injected a dependency into nuxtApp in a plugin, and the code is as follows.

``` test.plugin
export default defineNuxtPlugin(async (_nuxtApp) => {
  _nuxtApp.provide('test',{testKey:testValue})
})
```
When I used it in a utility class, this error occurred.

the util code 
```utils/test.util.ts
 import { useNuxtApp } from '#imports'
export class test{
  constructor(){
    const { test } = useNuxtApp()
  }
}
```

this error
```
Error: [unimport] failed to find "useNuxtApp" imported from "#imports"          
```

How should I handle this?thanks

**Comment by danielroe** [comment]
Please open a new issue with a reproduction [here](https://github.com/nuxt/nuxt/issues/new?assignees=&labels=pending+triage&projects=&template=bug-report.yml) - I'd love to help! 🙏
